sudo: required
services: 
  - docker

before_install:
  - docker build -t wissallaassilia/docker-react -f Dockerfile.dev .
script: # -e CI=true to exit the test
  - docker run -e CI=true wissallaassilia/docker-react npm run test